### ISSUE TITLE
Oracle Linux 7

### ISSUE THREAD

**Issue by kikitux** [anthshor/oracle_build#1]
Hello, according to the [Oracle GRID for Linux documentation](https://docs.oracle.com/database/121/CWLIN/prelinux.htm#CHDDJBJF) Oracle linux 7 is supported

can we use [kikitux/oracle7](https://atlas.hashicorp.com/kikitux/boxes/oracle7) ??

**Comment by kikitux** [comment]
![image](https://cloud.githubusercontent.com/assets/1255709/5996133/f0c7815e-ab08-11e4-8d0c-37159945e89c.png)

**Comment by kikitux** [comment]
Table 4-1 x86-64 Linux 7 Minimum Operating System Requirements

Item    Requirements
SSH Requirement

Ensure that OpenSSH is installed on your servers. OpenSSH is the required SSH software.

Oracle Linux 7

Subscribe to the Oracle Linux 7 channel on the Unbreakable Linux Network, or configure a yum repository from the Oracle public yum site, and then install the Oracle Preinstallation RPM. This RPM installs all required kernel packages for Oracle Grid Infrastructure and Oracle Database installations, and performs other system configuration.

Supported distributions:

Oracle Linux 7 with the Unbreakable Enterprise kernel: 3.8.13-33.el7uek.x86_64 or later
Oracle Linux 7 with the Red Hat Compatible kernel: 3.10.0-54.0.1.el7.x86_64 or later
Red Hat Enterprise Linux 7

Supported distributions:

Red Hat Enterprise Linux 7: 3.10.0-54.0.1.el7.x86_64 or later
Packages for Oracle Linux 7 and Red Hat Enterprise Linux 7

The following packages (or later versions) must be installed:

binutils-2.23.52.0.1-12.el7.x86_64 
compat-libcap1-1.10-3.el7.x86_64 
gcc-4.8.2-3.el7.x86_64 
gcc-c++-4.8.2-3.el7.x86_64 
glibc-2.17-36.el7.i686 
glibc-2.17-36.el7.x86_64 
glibc-devel-2.17-36.el7.i686 
glibc-devel-2.17-36.el7.x86_64 
libaio-0.3.109-9.el7.i686 
libaio-0.3.109-9.el7.x86_64 
libaio-devel-0.3.109-9.el7.i686 
libaio-devel-0.3.109-9.el7.x86_64 
ksh
make-3.82-19.el7.x86_64 
libXi-1.7.2-1.el7.i686 
libXi-1.7.2-1.el7.x86_64 
libXtst-1.2.2-1.el7.i686 
libXtst-1.2.2-1.el7.x86_64 
libgcc-4.8.2-3.el7.i686 
libgcc-4.8.2-3.el7.x86_64 
libstdc++-4.8.2-3.el7.i686 
libstdc++-4.8.2-3.el7.x86_64 
libstdc++-devel-4.8.2-3.el7.i686 
libstdc++-devel-4.8.2-3.el7.x86_64 
sysstat-10.1.5-1.el7.x86_64
Note: Oracle Universal Installer requires an X Window System (for example, libx). The libx packages are part of a default Linux installation. If you install Linux using an Oracle Preinstallation RPM, then the libx packages are installed as part of that RPM. If you perform an install on a system with a reduced set of packages, then you must ensure that libx is installed.

**Comment by anthshor** [comment]
Hi Alvaro,

Thanks for your advice. 
Fixed by https://github.com/anthshor/oracle_build/commit/560ada62748ac88b3f808511da02a7dcc403cdcb
