### ISSUE TITLE
Oracle 11.2 is out of premier support

### ISSUE THREAD

**Issue by kikitux** [anthshor/oracle_build#2]
According [Oracle lifetime support](http://www.oracle.com/us/support/library/lifetime-support-technology-069183.pdf) 11.2 is out of premier support

Can we use 12.1.0.2.3 ?

**Comment by kikitux** [comment]
![image](https://cloud.githubusercontent.com/assets/1255709/5996137/11267b1c-ab09-11e4-8c9d-aee26c7b7143.png)

**Comment by anthshor** [comment]
Oracle 12.1.0.2.3 will now be used going forward, for the database instead of 11gR2. 
The oracle-rdbms-server-11gR2-preinstall has been replaced with the oracle-rdbms-12cR1-preinstall package in preparation for this.

Thanks.

**Comment by kikitux** [comment]
fixed by https://github.com/anthshor/oracle_build/commit/560ada62748ac88b3f808511da02a7dcc403cdcb
