### ISSUE TITLE
 ensure => "latest"

### ISSUE THREAD

**Issue by kikitux** [anthshor/oracle_build#3]
Hello, 

on [lines 6 to 9 of site.pp](https://github.com/anthshor/oracle_build/blob/master/manifests/site.pp#L6-L9)

The following text is available:

``` ruby
package {"openssh":
  ensure => installed,
  allow_virtual => false,
}
```

It's possible to replace with `ensure => "latest"` ??

http://www.puppetcookbook.com/posts/latest-package.html

**Comment by kikitux** [comment]
same for

``` ruby
package {"oracle-rdbms-server-12cR1-preinstall":
  ensure  => installed,
  allow_virtual => false,
}
```

**Comment by anthshor** [comment]
Fixed in https://github.com/anthshor/oracle_build/commit/ba4c23effa66cb72dbcff3364d74e97691d1b967
Thanks.
