### ISSUE TITLE
GHOST glibc bug

### ISSUE THREAD

**Issue by kikitux** [anthshor/oracle_build#4]
In order to be safe, can we ensure we are in the latest glibc?

[ELSA-2015-0092 Critical: Oracle Linux 7 glibc security update](https://oss.oracle.com/pipermail/el-errata/2015-January/004812.html)

I think an ensure code in site.pp similar to the others should be fine.

**Comment by kikitux** [comment]
any update? this bug is critical

**Comment by anthshor** [comment]
Fixed in https://github.com/anthshor/oracle_build/commit/0ee56cfad673d10125d7368db65494ad4032a1da
Thanks

**Comment by kikitux** [comment]
where is the updated vagrant up log ??

**Comment by anthshor** [comment]
Now added.
